upstream laravel_backend {
    least_conn;
    server laravel-1:9000;
    server laravel-2:9000;
    server laravel-3:9000;
}

server {
    listen 80;
    server_name locsystem.tec.br;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name locsystem.tec.br;

    ssl_certificate /etc/letsencrypt/live/locsystem.tec.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/locsystem.tec.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    # =========================
    # SWAGGER JSON
    # =========================
    location = /docs {

        include fastcgi_params;

        fastcgi_pass laravel_backend;

        fastcgi_param SCRIPT_FILENAME /var/www/laravel/public/index.php;

        fastcgi_param DOCUMENT_ROOT /var/www/laravel/public;

        fastcgi_param REQUEST_URI /docs;

        fastcgi_param QUERY_STRING $query_string;
    }

    # =========================
    # SWAGGER UI
    # =========================
    location = /api/documentation {

        include fastcgi_params;

        fastcgi_pass laravel_backend;

        fastcgi_param SCRIPT_FILENAME /var/www/laravel/public/index.php;

        fastcgi_param DOCUMENT_ROOT /var/www/laravel/public;

        fastcgi_param REQUEST_URI /api/documentation;

        fastcgi_param QUERY_STRING $query_string;

        fastcgi_param HTTP_AUTHORIZATION $http_authorization;

    }

    # =========================
    # SWAGGER ASSETS
    # =========================
    location ^~ /docs/asset/ {

        include fastcgi_params;

        fastcgi_pass laravel_backend;

        fastcgi_param SCRIPT_FILENAME /var/www/laravel/public/index.php;

        fastcgi_param DOCUMENT_ROOT /var/www/laravel/public;

        fastcgi_param REQUEST_URI $request_uri;

        fastcgi_param QUERY_STRING $query_string;
    }

    # =========================
    # SWAGGER UI ASSETS
    # =========================
    location ^~ /api/documentation/asset/ {

       include fastcgi_params;
       
       fastcgi_pass laravel_backend;
       
       fastcgi_param SCRIPT_FILENAME /var/www/laravel/public/index.php;
       
       fastcgi_param DOCUMENT_ROOT /var/www/laravel/public;
       
       fastcgi_param REQUEST_URI $request_uri;
       
       fastcgi_param QUERY_STRING $query_string;

       fastcgi_param HTTP_AUTHORIZATION $http_authorization;

    }

    # =========================
    # MAILHOG
    # =========================
    location /mailhog/ {

       rewrite ^/mailhog/(.*)$ /$1 break;

       proxy_pass http://mailhog-container:8025;

       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_connect_timeout 60s;
       proxy_send_timeout 60s;
       proxy_read_timeout 60s;

    }

    # =========================
    # API LARAVEL
    # =========================
    location /api/ {

       try_files $uri $uri/ /index.php?$query_string;

    }

    location ~ .php$ {

       include fastcgi_params;

       fastcgi_pass laravel_backend;

       fastcgi_param SCRIPT_FILENAME /var/www/laravel/public$fastcgi_script_name;

       fastcgi_param DOCUMENT_ROOT /var/www/laravel/public;

       fastcgi_param HTTP_AUTHORIZATION $http_authorization;

    }

    # =========================
    # REACT
    # =========================i
    root /var/www/react/dist;

    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
