upstream laravel_backend {
    least_conn;

    server laravel-1:9000;
    server laravel-2:9000;
    server laravel-3:9000;
}

# =========================
# HTTP -> HTTPS
# =========================
server {
    listen 80;
    server_name locsystem.tec.br;

    return 301 https://$host$request_uri;
}

# =========================
# HTTPS
# =========================
server {

    listen 443 ssl;
    server_name locsystem.tec.br;

    ssl_certificate /etc/letsencrypt/live/locsystem.tec.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/locsystem.tec.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    # =========================
    # REACT FRONTEND
    # =========================
    root /var/www/react/dist;

    index index.html;

    location / {

        try_files $uri $uri/ /index.html;
    }

    # =========================
    # LARAVEL API
    # =========================
    location /api/ {

        root /var/www/laravel/public;

        try_files $uri /index.php?$query_string;

        include fastcgi_params;

        fastcgi_pass laravel_backend;

        fastcgi_param SCRIPT_FILENAME /var/www/laravel/public/index.php;

        fastcgi_param DOCUMENT_ROOT /var/www/laravel/public;

        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    }

    # =========================
    # PHP
    # =========================
    location ~ \.php$ {

        root /var/www/laravel/public;

        include fastcgi_params;

        fastcgi_pass laravel_backend;

        fastcgi_param SCRIPT_FILENAME /var/www/laravel/public$fastcgi_script_name;

        fastcgi_param DOCUMENT_ROOT /var/www/laravel/public;

        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    }

    # =========================
    # BLOCK HIDDEN FILES
    # =========================
    location ~ /\.ht {
        deny all;
    }
}
